"""
finalizer_agent.py — Compile CLAUDE.md from all approved PLANNER/ files.

Single responsibility: given a dict of {filename: content} for every file in
PLANNER/, produce a summarised CLAUDE.md (≤ 300 lines) via a single LLM call.

The agent only *generates* content — the Orchestrator is responsible for
writing the file to disk.
"""

from __future__ import annotations

from langchain_core.messages import SystemMessage, HumanMessage
from planner.agents._base import invoke_llm_safe, strip_markdown_fence


# ── Source files and their corresponding CLAUDE.md sections ──────────────

_FILE_SECTION_MAP: list[tuple[str, str]] = [
    ("StructuredIdea.md", "Project Summary"),
    ("TRD.md",            "Tech Stack"),
    ("ImplementationPlan.md", "Folder Structure"),
    ("Rules.md",          "Coding Rules (Critical)"),
    ("Constraints.md",    "Hard Constraints"),
    ("Schema.md",         "Data Model (Summary)"),
    ("TRD.md",            "Key API Endpoints"),
    ("AppFlow.md",        "Active Module"),
]

# All source files we consider (de-duplicated)
_ALL_SOURCE_FILES: list[str] = list(dict.fromkeys(
    fname for fname, _ in _FILE_SECTION_MAP
))


# ── System prompt ────────────────────────────────────────────────────────

SYSTEM_PROMPT = """\
You are a senior technical writer producing a CLAUDE.md execution-context \
document for a coding AI agent.

You will receive the contents of several planning documents from the \
PLANNER/ directory.  Your job is to **summarise** them into a single, \
concise CLAUDE.md that a coding agent can use as its operating manual.

## Output Structure (use these exact headings)

```
# CLAUDE.md
> Auto-generated by PlannerX /finalize. Do not edit manually.
> Regenerate with /finalize after planning changes.

## Project Summary
[3–5 sentences from StructuredIdea.md]

## Tech Stack
[Exact versions from TRD.md. Table format: Layer | Technology | Version]

## Folder Structure
[Key directories from ImplementationPlan.md. One line per dir with purpose.]

## Coding Rules (Critical)
[Top 5–10 rules from Rules.md that affect day-to-day code writing. Bullets.]

## Hard Constraints
[Must-never-do list from Constraints.md. Bullets.]

## Data Model (Summary)
[Key tables + primary columns only from Schema.md. Not full schema.]

## Key API Endpoints
[Core endpoints from TRD.md. Method + path + one-line purpose only.]

## Active Module
[Currently active module name, if any. Otherwise write "None".]
```

## Rules you MUST follow:
1. **NEVER copy-paste** verbatim from source files — summarise and distil.
2. Total output MUST be **under 300 lines**.  If you need to cut, drop \
   "Key API Endpoints" first, then "Data Model (Summary)".
3. For any section whose source file is marked `[EMPTY]`, output exactly: \
   `[Not available — <filename> was not generated]`
4. Write clean Markdown.  Do NOT wrap the whole output in code fences.
5. Do NOT add sections beyond the structure above.
"""


# ── Context-binding appendix (carried over from the old implementation) ──

_CONTEXT_BINDING_SECTION = """\

## Context Binding & Coding Instructions

This file serves as the master execution context for any coding agent \
(such as Claude Code or another coding AI) operating on this repository.

### Context Guidelines:
- Use **PRD.md** under `PLANNER/` for product requirements, scope, \
features, and success metrics.
- Use **TRD.md** under `PLANNER/` for technical stack specifications, \
architecture overview, and API interfaces.
- Use **Schema.md** under `PLANNER/` for database schemas, models, \
and relationships.
- Use **AppFlow.md** under `PLANNER/` for user journey flows, view maps, \
and UX state transitions.
- Use **DesignDecisions.md** under `PLANNER/` for historical architectural \
decisions, justifications, and trade-offs.
- Use **Rules.md** under `PLANNER/` for project-level coding rules, \
folder layouts, and styling conventions.
- Use **Constraints.md** under `PLANNER/` for system/environment limitations.
- Use **ImplementationPlan.md** under `PLANNER/` as the phased, \
checked-off implementation path.
- Check the **MODULES/** directory under `PLANNER/` for detailed modular \
spec sheets.
- Check the **ARCHITECTURE_DIAGRAMS/** directory under `PLANNER/` for \
system architecture, design, and data flow ASCII diagrams.

### Coding Agent Constraint:
The coding agent MUST strictly bind its execution and implementation \
choices to the detailed documents and rules located under the `PLANNER/` \
directory.  Do not deviate from the constraints, technical architectures, \
schemas, or design decision records defined therein.
"""


# ── Agent function ───────────────────────────────────────────────────────

def finalizer_agent(files: dict[str, str]) -> dict:
    """Compile a summarised CLAUDE.md from all PLANNER/ file contents.

    Args:
        files: A dict mapping filenames (e.g. ``"TRD.md"``) to their full
               text content.  Missing keys or empty values are treated as
               "not generated".

    Returns:
        A dict with two keys:

        - ``claude_md_content`` (str): The full CLAUDE.md text ready to be
          written to disk.
        - ``warnings`` (list[str]): Human-readable warnings for any files
          that were missing or empty.
    """
    warnings: list[str] = []

    # ── Build the user message with clear markers per source file ────
    user_parts: list[str] = [
        "Below are the contents of each planning document.  "
        "Summarise them into the CLAUDE.md structure described above.\n"
    ]

    for filename in _ALL_SOURCE_FILES:
        content = files.get(filename, "").strip()
        if not content:
            user_parts.append(
                f"=== {filename} ===\n[EMPTY]\n"
            )
            warnings.append(f"{filename} was empty — skipped")
        else:
            user_parts.append(
                f"=== {filename} ===\n{content}\n"
            )

    # Include any extra files that weren't in the standard map
    # (e.g. PRD.md, DesignDecisions.md) as supplementary context
    extra_files = sorted(
        fname for fname in files
        if fname not in _ALL_SOURCE_FILES and files[fname].strip()
    )
    for filename in extra_files:
        user_parts.append(
            f"=== {filename} (supplementary) ===\n{files[filename].strip()}\n"
        )

    user_message = "\n".join(user_parts)

    # ── Single LLM call ─────────────────────────────────────────────
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=user_message),
    ]
    raw_response = invoke_llm_safe(messages)
    llm_content = strip_markdown_fence(raw_response)

    # ── Assemble final CLAUDE.md ─────────────────────────────────────
    # The LLM output already contains the structured sections.
    # Append the static Context Binding section that agents rely on.
    claude_md_content = llm_content.rstrip() + "\n" + _CONTEXT_BINDING_SECTION

    return {
        "claude_md_content": claude_md_content,
        "warnings": warnings,
    }
